name: Build Design Tokens

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build design tokens
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: design-tokens-build
        path: dist/
        retention-days: 30
        
    - name: List generated files
      run: |
        echo "Generated design token files:"
        ls -la dist/
        echo ""
        echo "CSS Variables:"
        head -20 dist/css/variables.css
        echo ""
        echo "JavaScript Tokens:"
        head -10 dist/js/tokens.js
